;=============================================================================;
; GLOSS - Generic Loader for Operating System Software                        ;
; An extensible and configurable bootloader.                                  ;
;-----------------------------------------------------------------------------;
; Copyright (C) 2013-2016 ~ Adrian J. Collado       [acollado@polaritech.com] ;
; Copyright (C) 2015-2016 ~ Polaritech, Inc.         [https://polaritech.com] ;
; All Rights Reserved                                                         ;
;=============================================================================;

%ifndef ASSEMBLYFUNCTIONS_IAPX86_ERROR_ERRORINC
%define ASSEMBLYFUNCTIONS_IAPX86_ERROR_ERRORINC

%include "Abort.inc"
%include "CriticalFailure.inc"

%endif ;ASSEMBLYFUNCTIONS_IAPX86_ERROR_ERRORINC